config/routes.rb
Rails.application.routes.draw do
  get 'main' => 'main#index'
  get 'static_pages/index'
  root 'main#index'
  resources :fillups

end

app/models/fillup.rb
class Fillup < ActiveRecord::Base

  validates :odometer, presence: true, uniqueness: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :volume, presence: true, numericality: { greater_than: 0 }

  def total
    self.volume * self.price
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fillups_controller.rb
class FillupsController < ApplicationController
  before_action :set_fillup, only: [:show, :edit, :update, :destroy]

  # GET /fillups
  # GET /fillups.json
  def index
    @fillups = Fillup.all
  end

  # GET /fillups/1
  # GET /fillups/1.json
  def show
  end

  # GET /fillups/new
  def new
    @fillup = Fillup.new
  end

  # GET /fillups/1/edit
  def edit
  end

  # POST /fillups
  # POST /fillups.json
  def create
    @fillup = Fillup.new(fillup_params)

    respond_to do |format|
      if @fillup.save
        format.html { redirect_to @fillup, notice: 'Fillup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fillup }
      else
        format.html { render action: 'new' }
        format.json { render json: @fillup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillups/1
  # PATCH/PUT /fillups/1.json
  def update
    respond_to do |format|
      if @fillup.update(fillup_params)
        format.html { redirect_to @fillup, notice: 'Fillup was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @fillup }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fillup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillups/1
  # DELETE /fillups/1.json
  def destroy
    @fillup.destroy
    respond_to do |format|
      format.html { redirect_to fillups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fillup
      @fillup = Fillup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fillup_params
      params.require(:fillup).permit(:odometer, :price, :volume, :date, :missed, :partial)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout false
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fillups_helper.rb
module FillupsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/fillups/_form.html.erb
<%= form_for(@fillup) do |f| %>
  <% if @fillup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fillup.errors.count, "error") %> prohibited this fillup from being saved:</h2>

      <ul>
      <% @fillup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :odometer %><br>
    <%= f.text_field :odometer %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :missed %><br>
    <%= f.check_box :missed %>
  </div>
  <div class="field">
    <%= f.label :partial %><br>
    <%= f.check_box :partial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fillups/edit.html.erb
<h1>Editing fillup</h1>

<%= render 'form' %>

<%= link_to 'Show', @fillup %> |
<%= link_to 'Back', fillups_path %>

app/views/fillups/index.html.erb
<h1>Listing fillups</h1>

<table>
  <thead>
    <tr>
      <th>Odometer</th>
      <th>Price</th>
      <th>Volume</th>
      <th>Date</th>
      <th>Missed</th>
      <th>Partial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fillups.each do |fillup| %>
      <tr>
        <td><%= fillup.odometer %></td>
        <td><%= fillup.price %></td>
        <td><%= fillup.volume %></td>
        <td><%= fillup.date %></td>
        <td><%= fillup.missed %></td>
        <td><%= fillup.partial %></td>
        <td><%= link_to 'Show', fillup %></td>
        <td><%= link_to 'Edit', edit_fillup_path(fillup) %></td>
        <td><%= link_to 'Destroy', fillup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fillup', new_fillup_path %>

app/views/fillups/new.html.erb
<h1>New fillup</h1>

<%= render 'form' %>

<%= link_to 'Back', fillups_path %>

app/views/fillups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Odometer:</strong>
  <%= @fillup.odometer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fillup.price %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @fillup.volume %>
</p>

<p>
  <strong>Date:</strong>
  <%= @fillup.date %>
</p>

<p>
  <strong>Missed:</strong>
  <%= @fillup.missed %>
</p>

<p>
  <strong>Partial:</strong>
  <%= @fillup.partial %>
</p>

<%= link_to 'Edit', edit_fillup_path(@fillup) %> |
<%= link_to 'Back', fillups_path %>

app/views/layouts/application.html.haml
!!! 5
%html{:"ng-app"=>"FillupApp"}
  %head
    %title Rails41Angular
    -# = stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js'
    = javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-route.min.js'
    = javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-resource.min.js'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js'
    = javascript_include_tag 'application', controller_name
    -# = javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js'
    = csrf_meta_tags
  %body
    = render "main/layout"
    .container
      = yield

app/views/main/_layout.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{"ng-controller" => "HeaderCtrl"}
  .navbar-header
    %button.navbar-toggle{type:"button", "data-toggle" => "collapse",
      "data-target" => "#bs-example-navbar-collapse-1",
      "ng-click" => "asideVisibleFlip()"}
      %i.entypo-menu#toggle-icon
    %a.navbar-brand{href: "/"} Rubulage
  .container-fluid
    .collapse.navbar-collapse
      %a.button.btn.btn-primary.navbar-btn{href: "/fillups/new"}
        %i.entypo-droplet.menu-icon.extra-margin
        New Fillup
      %p.navbar-text.navbar-right
        %a.navbar-link{href: "#"} Scott Humphries

%aside{"ng-controller" => "AsideCtrl",
  "ng-class" => "{ 'visible' : asideVisible }"}
  .sidebar-inner
    .main-menu
      %ul
        %li.active
          %a{href: "/"}
            %i.entypo-gauge.menu-icon
            %span.text Dashboard
        %li.visible-xs
          %a{href: "/fillups"}
            %i.entypo-droplet.menu-icon.extra-margin
            %span.text New Fillup
        %li
          %a{href: "/fillups"}
            %i.entypo-water.menu-icon
            %span.text Fillups
        %li
          %a{href: "javascript:void(0);"}
            %i.entypo-chart-line.menu-icon
            %span.text Stats

.container-fluid{"ng-controller" => "IndexCtrl", "ng-view" => true}

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Static Title</title>
  </head>
  <body>
    <h1>Static H1</h1>
    <p>
      This is the static page.
    </p>
    <a href="login">Login</a>
  </body>
</html>